import type { Case, Scenario } from '../models/workflow';
const review = (outcome: Case['medical']['outcome'], assignee: string, comments = '') => ({ outcome, assignee, comments });
const base = (id:string, beneficiaryName:string, hospital:string): Case => ({ id, caseRef:id, beneficiaryName, hospital, broadStatus:'Under Review', verification:'complete', medical:review('approved','Dr. N. Shah','Medical eligibility confirmed.'), social:review('approved','R. Das','Home situation reviewed.'), financial:review('approved','K. Iyer','Financial need established.'), sponsor:{state:'ready', amount:'₹ 1,25,000', notes:'Proposed based on demonstrated need and treatment estimate.'}, director:{state:'not ready',comments:''}, panelRecommendation:'Panel recommends support within the proposed amount.' });
export const scenarioCases = (scenario: Scenario): Case[] => {
 const normal=base('DEMO-NFI-001','Baby Aarav Demo','Sunrise Children’s Hospital (Demo)'); normal.verification='pending'; normal.medical=review('not assigned','Medical Review Team'); normal.social=review('not assigned','Social Review Team'); normal.financial=review('not assigned','Financial Review Team'); normal.sponsor={state:'unavailable',amount:'',notes:''};
 const financial=base('DEMO-NFI-003','Baby Kabir Demo','Greenfield Hospital (Demo)'); financial.financial=review('in progress','K. Iyer'); financial.sponsor={state:'unavailable',amount:'',notes:''};
 const ready=base('DEMO-NFI-004','Baby Aria Demo','Riverside Children’s Hospital (Demo)');
 const medical=base('DEMO-NFI-005','Baby Diya Demo','Willow Care Hospital (Demo)'); medical.medical=review('need more information','Dr. N. Shah','Please provide the updated treatment estimate.'); medical.social=review('not assigned','Social Review Team'); medical.financial=review('not assigned','Financial Review Team'); medical.sponsor={state:'unavailable',amount:'',notes:''};
 const revision=base('DEMO-NFI-002','Baby Meera Demo','Hope Neonatal Centre (Demo)'); revision.sponsor.state='pending director'; revision.director={state:'pending',comments:''};
 const rejected=base('DEMO-NFI-008','Baby Tara Demo','CarePoint Hospital (Demo)'); rejected.sponsor.state='pending director'; rejected.director={state:'pending',comments:''};
 const approved=base('DEMO-NFI-006','Baby Zoya Demo','Harmony Children’s Hospital (Demo)'); approved.broadStatus='Approved'; approved.beneficiaryNumber='DEMO-BEN-6201'; approved.sponsor.state='pending director'; approved.director={state:'approved',comments:'Sponsorship approved for the proposed amount.',date:'28 Aug 2026'};
 switch(scenario){case 'Normal Approval': return [normal,medical,financial,ready,revision,rejected,approved];case 'Financial Review Pending':return [financial,normal,medical,ready,revision,rejected,approved];case 'Medical Needs More Information':return [medical,financial,normal,ready,revision,rejected,approved];case 'Director Revision':return [revision,financial,normal,medical,ready,rejected,approved];case 'Director Rejection':return [rejected,revision,financial,normal,medical,ready,approved];case 'Approved Case':return [approved,revision,financial,normal,medical,ready,rejected];}
};
